name: simple-notes-application

services:
  backend:
    build: backend/
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - FRONT_HOST=http://localhost:8080
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
        timeout: 10s
        retries: 10
  frontend:
    build: 
      context: frontend/
      args:
        - VITE_BE_HOST=127.0.0.1:3000
    ports:
      - 8080:3000
    depends_on:
      - backend